caps=[
    "Be yourself; everyone else is already taken",
    "You've gotta dance like there's nobody watching,Love like you'll never be hurt,Sing like there's nobody listening,And live like it's heaven on earth",
    "Be the change that you wish to see in the world",
    "Live as if you were to die tomorrow. Learn as if you were to live forever",
    "Darkness cannot drive out darkness: only light can do that. Hate cannot drive out hate: only love can do that",
    "Without music, life would be a mistake",
    "We accept the love we think we deserve",
    "Imperfection is beauty, madness is genius and it's better to be absolutely ridiculous than absolutely boring",
    "There are only two ways to live your life. One is as though nothing is a miracle. The other is as though everything is a miracle",
    "We are all in the gutter, but some of us are looking at the stars",
    "Fairy tales are more than true: not because they tell us that dragons exist, but because they tell us that dragons can be beaten",
    "Yesterday is history, tomorrow is a mystery, today is a gift of God, which is why we call it the present",
    "I have not failed. I've just found 10,000 ways that won't work",
    "The opposite of love is not hate, it's indifference. The opposite of art is not ugliness, it's indifference. The opposite of faith is not heresy, it's indifference. And the opposite of life is not death, it's indifference",
    "I am enough of an artist to draw freely upon my imagination. Imagination is more important than knowledge. Knowledge is limited. Imagination encircles the world",
    "You have brains in your head. You have feet in your shoes. You can steer yourself any direction you choose. You're on your own. And you know what you know. And YOU are the one who'll decide where to go..",
    "It is never too late to be what you might have been",
    "This life is what you make it. No matter what, you're going to mess up sometimes, it's a universal truth. But the good part is you get to decide how you're going to mess it up. Girls will be your friends - they'll act like it anyway. But just remember, some come, some go. The ones that stay with you through everything - they're your true best friends. Don't let go of them. Also remember, sisters make the best friends in the world. As for lovers, well, they'll come and go too. And baby, I hate to say it, most of them - actually pretty much all of them are going to break your heart, but you can't give up because if you give up, you'll never find your soulmate. You'll never find that half who makes you whole and that goes for everything. Just because you fail once, doesn't mean you're gonna fail at everything. Keep trying, hold on, and always, always, always believe in yourself, because if you don't, then who will, sweetie? So keep your head high, keep your chin up, and most importantly, keep smiling, because life's a beautiful thing and there's so much to smile about",
    "There is no greater agony than bearing an untold story inside you",
    "Everything you can imagine is real",
    "You can never get a cup of tea large enough or a book long enough to suit me",
    "Life isn't about finding yourself. Life is about creating yourself",
    "To the well-organized mind, death is but the next great adventure",
    "Do what you can, with what you have, where you are",
    "Success is not final, failure is not fatal: it is the courage to continue that counts",
    "Listen to the mustn'ts, child. Listen to the don'ts. Listen to the shouldn'ts, the impossibles, the won'ts. Listen to the never haves, then listen close to me... Anything can happen, child. Anything can be",
    "When one door of happiness closes, another opens; but often we look so long at the closed door that we do not see the one which has been opened for us",
    "So, this is my life. And I want you to know that I am both happy and sad and I'm still trying to figure out how that could be",
    "And, when you want something, all the universe conspires in helping you to achieve it",
    "You may say I'm a dreamer, but I'm not the only one. I hope someday you'll join us. And the world will live as one",
    "Be yourself; everyone else is already taken",
    "You've gotta dance like there's nobody watching,Love like you'll never be hurt,Sing like there's nobody listening,And live like it's heaven on earth",
    "Be the change that you wish to see in the world",
    "Live as if you were to die tomorrow. Learn as if you were to live forever",
    "Darkness cannot drive out darkness: only light can do that. Hate cannot drive out hate: only love can do that",
    "Without music, life would be a mistake",
    "We accept the love we think we deserve",
    "Imperfection is beauty, madness is genius and it's better to be absolutely ridiculous than absolutely boring",
    "There are only two ways to live your life. One is as though nothing is a miracle. The other is as though everything is a miracle",
    "We are all in the gutter, but some of us are looking at the stars",
    "Fairy tales are more than true: not because they tell us that dragons exist, but because they tell us that dragons can be beaten",
    "Yesterday is history, tomorrow is a mystery, today is a gift of God, which is why we call it the present",
    "I have not failed. I've just found 10,000 ways that won't work",
    "The opposite of love is not hate, it's indifference. The opposite of art is not ugliness, it's indifference. The opposite of faith is not heresy, it's indifference. And the opposite of life is not death, it's indifference",
    "I am enough of an artist to draw freely upon my imagination. Imagination is more important than knowledge. Knowledge is limited. Imagination encircles the world",
    "You have brains in your head. You have feet in your shoes. You can steer yourself any direction you choose. You're on your own. And you know what you know. And YOU are the one who'll decide where to go..",
    "It is never too late to be what you might have been",
    "This life is what you make it. No matter what, you're going to mess up sometimes, it's a universal truth. But the good part is you get to decide how you're going to mess it up. Girls will be your friends - they'll act like it anyway. But just remember, some come, some go. The ones that stay with you through everything - they're your true best friends. Don't let go of them. Also remember, sisters make the best friends in the world. As for lovers, well, they'll come and go too. And baby, I hate to say it, most of them - actually pretty much all of them are going to break your heart, but you can't give up because if you give up, you'll never find your soulmate. You'll never find that half who makes you whole and that goes for everything. Just because you fail once, doesn't mean you're gonna fail at everything. Keep trying, hold on, and always, always, always believe in yourself, because if you don't, then who will, sweetie? So keep your head high, keep your chin up, and most importantly, keep smiling, because life's a beautiful thing and there's so much to smile about",
    "There is no greater agony than bearing an untold story inside you",
    "Everything you can imagine is real",
    "You can never get a cup of tea large enough or a book long enough to suit me",
    "Life isn't about finding yourself. Life is about creating yourself",
    "To the well-organized mind, death is but the next great adventure",
    "Do what you can, with what you have, where you are",
    "Success is not final, failure is not fatal: it is the courage to continue that counts",
    "Listen to the mustn'ts, child. Listen to the don'ts. Listen to the shouldn'ts, the impossibles, the won'ts. Listen to the never haves, then listen close to me... Anything can happen, child. Anything can be",
    "When one door of happiness closes, another opens; but often we look so long at the closed door that we do not see the one which has been opened for us",
    "So, this is my life. And I want you to know that I am both happy and sad and I'm still trying to figure out how that could be",
    "And, when you want something, all the universe conspires in helping you to achieve it",
    "You may say I'm a dreamer, but I'm not the only one. I hope someday you'll join us. And the world will live as one",
    "Our deepest fear is not that we are inadequate. Our deepest fear is that we are powerful beyond measure. It is our light, not our darkness that most frightens us. We ask ourselves, 'Who am I to be brilliant, gorgeous, talented, fabulous?' Actually, who are you not to be? You are a child of God. Your playing small does not serve the world. There is nothing enlightened about shrinking so that other people won't feel insecure around you. We are all meant to shine, as children do. We were born to make manifest the glory of God that is within us. It's not just in some of us; it's in everyone. And as we let our own light shine, we unconsciously give other people permission to do the same. As we are liberated from our own fear, our presence automatically liberates others",
    "It’s no use going back to yesterday, because I was a different person then",
    "It's the possibility of having a dream come true that makes life interesting",
    "What you're supposed to do when you don't like a thing is change it. If you can't change it, change the way you think about it. Don't complain",
    "He’s not perfect. You aren’t either, and the two of you will never be perfect. But if he can make you laugh at least once, causes you to think twice, and if he admits to being human and making mistakes, hold onto him and give him the most you can. He isn’t going to quote poetry, he’s not thinking about you every moment, but he will give you a part of him that he knows you could break. Don’t hurt him, don’t change him, and don’t expect for more than he can give. Don’t analyze. Smile when he makes you happy, yell when he makes you mad, and miss him when he’s not there. Love hard when there is love to be had. Because perfect guys don’t exist, but there’s always one guy that is perfect for you",
    "A person's a person, no matter how small",
    "When we honestly ask ourselves which person in our lives mean the most to us, we often find that it is those who, instead of giving advice, solutions, or cures, have chosen rather to share our pain and touch our wounds with a warm and tender hand. The friend who can be silent with us in a moment of despair or confusion, who can stay with us in an hour of grief and bereavement, who can tolerate not knowing, not curing, not healing and face with us the reality of our powerlessness, that is a friend who cares",
    "You can't live your life for other people. You've got to do what's right for you, even if it hurts some people you love",
    "Well-behaved women seldom make history",
    "When I despair, I remember that all through history the way of truth and love have always won. There have been tyrants and murderers, and for a time, they can seem invincible, but in the end, they always fall. Think of it--always",
    "So we beat on, boats against the current, borne back ceaselessly into the past",
    "Nothing is impossible, the word itself says 'I'm possible'",
    "I can't give you a sure-fire formula for success, but I can give you a formula for failure: try to please everybody all the time",
    "[...]the only people for me are the mad ones, the ones who are mad to live, mad to talk, mad to be saved, desirous of everything at the same time, the ones who never yawn or say a commonplace thing, but burn, burn, burn like fabulous yellow roman candles exploding like spiders across the stars and in the middle you see the blue centerlight pop and everybody goes “Awww",
    "Do what you feel in your heart to be right – for you’ll be criticized anyway",
    "Never doubt that a small group of thoughtful, committed, citizens can change the world. Indeed, it is the only thing that ever has",
    "Happiness is not something ready made. It comes from your own actions",
    "Peace begins with a smile.",
    "Do not read, as children do, to amuse yourself, or like the ambitious, for the purpose of instruction. No, read in order to live",
    "Imagining the future is a kind of nostalgia. (...) You spend your whole life stuck in the labyrinth, thinking about how you'll escape it one day, and how awesome it will be, and imagining that future keeps you going, but you never do it. You just use the future to escape the present",
    "What lies behind us and what lies before us are tiny matters compared to what lies within us",
    "For attractive lips, speak words of kindness.For lovely eyes, seek out the good in people.For a slim figure, share your food with the hungry.For beautiful hair, let a child run his fingers through it once a day.For poise, walk with the knowledge you’ll never walk alone....We leave you a tradition with a future.The tender loving care of human beings will never become obsolete.People even more than things have to be restored, renewed, revived, reclaimed and redeemed and redeemed and redeemed.Never throw out anybody.Remember, if you ever need a helping hand, you’ll find one at the end of your arm.As you grow older, you will discover that you have two hands: one for helping yourself, the other for helping others.Your “good old days” are still ahead of you, may you have many of them",
    "Friendship is unnecessary, like philosophy, like art.... It has no survival value; rather it is one of those things which give value to survival",
    "Promise YourselfTo be so strong that nothingcan disturb your peace of mind.To talk health, happiness, and prosperityto every person you meet.To make all your friends feelthat there is something in themTo look at the sunny side of everythingand make your optimism come true.To think only the best, to work only for the best,and to expect only the best.To be just as enthusiastic about the success of othersas you are about your own.To forget the mistakes of the pastand press on to the greater achievements of the future.To wear a cheerful countenance at all timesand give every living creature you meet a smile.To give so much time to the improvement of yourselfthat you have no time to criticize others.To be too large for worry, too noble for anger, too strong for fear,and too happy to permit the presence of trouble.To think well of yourself and to proclaim this fact to the world,not in loud words but great deeds.To live in faith that the whole world is on your sideso long as you are true to the best that is in you",
    "I hope she'll be a fool -- that's the best thing a girl can be in this world, a beautiful little fool",
    "Whatever you are, be a good one",
    "May you live every day of your life",
    "Two wrongs don't make a right, but they make a good excuse",
    "Who controls the past controls the future. Who controls the present controls the past",
    "First they ignore you. Then they ridicule you. And then they attack you and want to burn you. And then they build monuments to you",
    "I believe that imagination is stronger than knowledge. That myth is more potent than history. That dreams are more powerful than facts. That hope always triumphs over experience. That laughter is the only cure for grief. And I believe that love is stronger than death",
    "If my life is going to mean anything, I have to live it myself",
    "And once the storm is over, you won’t remember how you made it through, how you managed to survive. You won’t even be sure, whether the storm is really over. But one thing is certain. When you come out of the storm, you won’t be the same person who walked in. That’s what this storm’s all about",
    "You can't stay in your corner of the Forest waiting for others to come to you. You have to go to them sometimes",
    "Isn't it nice to think that tomorrow is a new day with no mistakes in it yet",
    "Attitude is a choice. Happiness is a choice. Optimism is a choice. Kindness is a choice. Giving is a choice. Respect is a choice. Whatever choice you make makes you. Choose wisely",
    "Hope is the thing with feathers That perches in the soul And sings the tune without the words And never stops at all",
    "You can talk with someone for years, everyday, and still, it won't mean as much as what you can have when you sit in front of someone, not saying a word, yet you feel that person with your heart, you feel like you have known the person for forever.... connections are made with the heart, not the tongue",
    "Pain is inevitable. Suffering is optional",
    "When I was 5 years old, my mother always told me that happiness was the key to life. When I went to school, they asked me what I wanted to be when I grew up. I wrote down ‘happy’. They told me I didn’t understand the assignment, and I told them they didn’t understand life",
    "If you're reading this...Congratulations, you're alive.If that's not something to smile about,then I don't know what is",
    "Always do what you are afraid to do",
    "Our lives begin to end the day we become silent about things that matter",
    "The mind is its own place, and in itself can make a heaven of hell, a hell of heaven.",
    "Talent hits a target no one else can hit. Genius hits a target no one else can see",
    "In the end, we will remember not the words of our enemies, but the silence of our friends",
    "Do not let your fire go out, spark by irreplaceable spark in the hopeless swamps of the not-quite, the not-yet, and the not-at-all. Do not let the hero in your soul perish in lonely frustration for the life you deserved and have never been able to reach. The world you desire can be won. It exists.. it is real.. it is possible.. it's yours",
    "It is so hard to leave—until you leave. And then it is the easiest goddamned thing in the world",
    "Don't be pushed around by the fears in your mind. Be led by the dreams in your heart",
    "Fantasy is hardly an escape from reality. It's a way of understanding it",
    "The world is indeed full of peril, and in it there are many dark places; but still there is much that is fair, and though in all lands love is now mingled with grief, it grows perhaps the greater",
    "Waiting is painful. Forgetting is painful. But not knowing which to do is the worst kind of suffering",
    "It is not the critic who counts; not the man who points out how the strong man stumbles, or where the doer of deeds could have done them better. The credit belongs to the man who is actually in the arena, whose face is marred by dust and sweat and blood; who strives valiantly; who errs, who comes short again and again, because there is no effort without error and shortcoming; but who does actually strive to do the deeds; who knows great enthusiasms, the great devotions; who spends himself in a worthy cause; who at the best knows in the end the triumph of high achievement, and who at the worst, if he fails, at least fails while daring greatly, so that his place shall never be with those cold and timid souls who neither know victory nor defeat",
    "Do not go where the path may lead, go instead where there is no path and leave a trail",
    "Instead of worrying about what you cannot control, shift your energy to what you can create",
    "Hell is empty and all the devils are here",
    "Never let your sense of morals prevent you from doing what is right",
    "If you can't fly then run, if you can't run then walk, if you can't walk then crawl, but whatever you do you have to keep moving forward",
    "I love to see a young girl go out and grab the world by the lapels. Life's a bitch. You've got to go out and kick ass",
    "If you remember me, then I don't care if everyone else forgets",
    "Turn your wounds into wisdom",
    "Take responsibility of your own happiness, never put it in other people’s hands",
    "When you have eliminated all which is impossible, then whatever remains, however improbable, must be the truth",
    "Be the reason someone smiles. Be the reason someone feels loved and believes in the goodness in people",
    "War is peace. Freedom is slavery. Ignorance is strength",
    "Be mindful. Be grateful. Be positive. Be true. Be kind",
    "Prayer is not asking. It is a longing of the soul. It is daily admission of one's weakness. It is better in prayer to have a heart without words than words without a heart",
    "Accept yourself, love yourself, and keep moving forward. If you want to fly, you have to give up what weighs you down",
    "It isn't what you have or who you are or where you are or what you are doing that makes you happy or unhappy. It is what you think about it",
    "What I need is the dandelion in the spring. The bright yellow that means rebirth instead of destruction. The promise that life can go on, no matter how bad our losses. That it can be good again",
    "Life is too short to waste your time on people who don’t respect, appreciate, and value you",
    "I don't trust people who don't love themselves and tell me, 'I love you.' ... There is an African saying which is: Be careful when a naked person offers you a shirt",
    "The future belongs to those who believe in the beauty of their dreams",
    "And, in the endThe love you takeis equal to the love you make",
    "I like living. I have sometimes been wildly, despairingly, acutely miserable, racked with sorrow; but through it all I still know quite certainly that just to be alive is a grand thing",
    "I am not sure exactly what heaven will be like, but I know that when we die and it comes time for God to judge us, he will not ask, 'How many good things have you done in your life?' rather he will ask, 'How much love did you put into what you did",
    "I do not fear death. I had been dead for billions and billions of years before I was born, and had not suffered the slightest inconvenience from it",
    "We’re all seeking that special person who is right for us. But if you’ve been through enough relationships, you begin to suspect there’s no right person, just different flavors of wrong. Why is this? Because you yourself are wrong in some way, and you seek out partners who are wrong in some complementary way. But it takes a lot of living to grow fully into your own wrongness. And it isn’t until you finally run up against your deepest demons, your unsolvable problems—the ones that make you truly who you are—that we’re ready to find a lifelong mate. Only then do you finally know what you’re looking for. You’re looking for the wrong person. But not just any wrong person: it's got to be the right wrong person—someone you lovingly gaze upon and think, “This is the problem I want to have.”I will find that special person who is wrong for me in just the right way",
    "Live the Life of Your Dreams: Be brave enough to live the life of your dreams according to your vision and purpose instead of the expectations and opinions of others",
    "It’s only after you’ve stepped outside your comfort zone that you begin to change, grow, and transform",
    "Don't judge each day by the harvest you reap but by the seeds that you plant",
    "But I know, somehow, that only when it is dark enough can you see the stars",
    "Believe in yourself. You are braver than you think, more talented than you know, and capable of more than you imagine",
    "More smiling, less worrying. More compassion, less judgment. More blessed, less stressed. More love, less hate",
    "Simplicity, patience, compassion.These three are your greatest treasures.Simple in actions and thoughts, you return to the source of being.Patient with both friends and enemies,you accord with the way things are.Compassionate toward yourself,you reconcile all beings in the world",
    "The past is a place of reference, not a place of residence; the past is a place of learning, not a place of living",
    "None but ourselves can free our minds",
    "Don't let the expectations and opinions of other people affect your decisions. It's your life, not theirs. Do what matters most to you; do what makes you feel alive and happy. Don't let the expectations and ideas of others limit who you are. If you let others tell you who you are, you are living their reality — not yours. There is more to life than pleasing people. There is much more to life than following others' prescribed path. There is so much more to life than what you experience right now. You need to decide who you are for yourself. Become a whole being. Adventure",
    "Don’t waste your time in anger, regrets, worries, and grudges. Life is too short to be unhappy",
    "The truth is, unless you let go, unless you forgive yourself, unless you forgive the situation, unless you realize that the situation is over, you cannot move forward",
    "Sometimes our light goes out, but is blown again into instant flame by an encounter with another human being",
    "Do what is right, not what is easy nor what is popular",
    "Clouds come floating into my life, no longer to carry rain or usher storm, but to add color to my sunset sky",
    "If you want to be happy, do not dwell in the past, do not worry about the future, focus on living fully in the present",
    "People say nothing is impossible, but I do nothing every day",
    "Don't JustDon't just learn, experience.Don't just read, absorb.Don't just change, transform.Don't just relate, advocate.Don't just promise, prove.Don't just criticize, encourage.Don't just think, ponder.Don't just take, give.Don't just see, feel.Don’t just dream, do. Don't just hear, listen.Don't just talk, act.Don't just tell, show.Don't just exist, live",
    "Even if you cannot change all the people around you, you can change the people you choose to be around. Life is too short to waste your time on people who don’t respect, appreciate, and value you. Spend your life with people who make you smile, laugh, and feel loved",
    "The things you do for yourself are gone when you are gone, but the things you do for others remain as your legacy",
    "You cannot control the behavior of others, but you can always choose how you respond to it",
    "Dare to BeWhen a new day begins, dare to smile gratefully.When there is darkness, dare to be the first to shine a light.When there is injustice, dare to be the first to condemn it.When something seems difficult, dare to do it anyway.When life seems to beat you down, dare to fight back.When there seems to be no hope, dare to find some.When you’re feeling tired, dare to keep going.When times are tough, dare to be tougher.When love hurts you, dare to love again.When someone is hurting, dare to help them heal.When another is lost, dare to help them find the way.When a friend falls, dare to be the first to extend a hand.When you cross paths with another, dare to make them smile.When you feel great, dare to help someone else feel great too.When the day has ended, dare to feel as you’ve done your best.Dare to be the best you can –At all times, Dare to be",
    "Life becomes easier and more beautiful when we can see the good in other people",
    "A painter should begin every canvas with a wash of black, because all things in nature are dark except where exposed by the light",
    "A woman's heart should be so hidden in God that a man has to seek Him just to find her",
    "It's kind of fun to do the impossible",
    "Pain is temporary. Quitting lasts forever",
    "The most important kind of freedom is to be what you really are. You trade in your reality for a role. You trade in your sense for an act. You give up your ability to feel, and in exchange, put on a mask. There can't be any large-scale revolution until there's a personal revolution, on an individual level. It's got to happen inside first",
    "Don't be afraid of your fears. They're not there to scare you. They're there to let you know that something is worth it",
    "When I was a little girl I used to read fairy tales. In fairy tales you meet Prince Charming and he's everything you ever wanted. In fairy tales the bad guy is very easy to spot. The bad guy is always wearing a black cape so you always know who he is. Then you grow up and you realize that Prince Charming is not as easy to find as you thought. You realize the bad guy is not wearing a black cape and he's not easy to spot; he's really funny, and he makes you laugh, and he has perfect hair",
    "I was smiling yesterday,I am smiling today and I will smile tomorrow.Simply because life is too short to cry for anything",
    "You never fail until you stop trying",
    "All the darkness in the world cannot extinguish the light of a single candle",
    "If you want to forget something or someone, never hate it, or never hate him/her. Everything and everyone that you hate is engraved upon your heart; if you want to let go of something, if you want to forget, you cannot hate",
    "HopeSmiles from the threshold of the year to come, Whispering 'it will be happier'..",
    "Start writing, no matter what. The water does not flow until the faucet is turned on",
    "The Chinese use two brush strokes to write the word 'crisis.' One brush stroke stands for danger; the other for opportunity. In a crisis, be aware of the danger--but recognize the opportunity",
    "Stories never really end...even if the books like to pretend they do. Stories always go on. They don't end on the last page, any more than they begin on the first page",
    "Why didn't I learn to treat everything like it was the last time. My greatest regret was how much I believed in the future",
    "To see a World in a Grain of Sand And a Heaven in a Wild Flower, Hold Infinity in the palm of your hand And Eternity in an hour",
    "Make improvements, not excuses. Seek respect, not attention",
    "Keep GoingYour hardest times often lead to the greatest moments of your life. Keep going. Tough situations build strong people in the end",
    "Pursue what catches your heart, not what catches your eyes",
    "You're off to Great Places!Today is your day!Your mountain is waiting,So... get on your way",
    "Success is not how high you have climbed, but how you make a positive difference to the world",
    "Well, nowIf little by little you stop loving meI shall stop loving youLittle by littleIf suddenly you forget meDo not look for meFor I shall already have forgotten youIf you think it long and mad the wind of banners that passes through my lifeAnd you decide to leave me at the shore of the heart where I have rootsRememberThat on that day, at that hour, I shall lift my armsAnd my roots will set off to seek another lan",
    "We have to allow ourselves to be loved by the people who really love us, the people who really matter. Too much of the time, we are blinded by our own pursuits of people to love us, people that don't even matter, while all that time we waste and the people who do love us have to stand on the sidewalk and watch us beg in the streets! It's time to put an end to this. It's time for us to let ourselves be loved",
    "It is the time you have wasted for your rose that makes your rose so important",
    "Learn to light a candle in the darkest moments of someone’s life. Be the light that helps others see; it is what gives life its deepest significance",
    "Don't say you don't have enough time. You have exactly the same number of hours per day that were given to Helen Keller, Pasteur, Michelangelo, Mother Teresa, Leonardo da Vinci, Thomas Jefferson, and Albert Einstein",
    "Once you have tasted flight, you will forever walk the earth with your eyes turned skyward, for there you have been, and there you will always long to return",
    "Be grateful for what you already have while you pursue your goals. If you aren’t grateful for what you already have, what makes you think you would be happy with more",
    "The secret of health for both mind and body is not to mourn for the past, nor to worry about the future, but to live the present moment wisely and earnestly",
    "One love, one heart, one destiny",
    "Believe in Your HeartBelieve in your heart that you're meant to live a life full of passion, purpose, magic and miracles",
    "If she's amazing, she won't be easy. If she's easy, she won't be amazing. If she's worth it, you wont give up. If you give up, you're not worthy. ... Truth is, everybody is going to hurt you; you just gotta find the ones worth suffering for",
    "Dance, when you're broken open. Dance, if you've torn the bandage off. Dance in the middle of the fighting. Dance in your blood. Dance when you're perfectly free",
    "No amount of regretting can change the past, and no amount of worrying can change the future",
    "Treat everyone with politeness and kindness, not because they are nice, but because you are",
    "So be sure when you step, Step with care and great tact. And remember that life's A Great Balancing Act. And will you succeed? Yes! You will, indeed! (98 and ¾ percent guaranteed) Kid, you'll move mountains",
    "Any fool can be happy. It takes a man with real heart to make beauty out of the stuff that makes us weep",
    "Start each day with a positive thought and a grateful heart",
    "Acts of Kindness:A random act of kindness, no matter how small, can make a tremendous impact on someone else's life",
    "It's not the face, but the expressions on it. It's not the voice, but what you say. It's not how you look in that body, but the thing you do with it. You are beautiful",
    "You is kind. You is smart. You is important",
    "Follow your heart, listen to your inner voice, stop caring about what others think",
    "Top 15 Things Money Can’t BuyTime. Happiness. Inner Peace. Integrity. Love. Character. Manners. Health. Respect. Morals. Trust. Patience. Class. Common sense. Dignity",
    "Understanding is the first step to acceptance, and only with acceptance can there be recovery",
    "Is 'fat' really the worst thing a human being can be? Is 'fat' worse than 'vindictive', 'jealous', 'shallow', 'vain', 'boring' or 'cruel'? Not to me"
]

usedCaps=[]